# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SLaXicon.org
description: > # this means to ignore newlines until "baseurl:"
  Personal website for Tom Green
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tmgreen.github.io" # the base hostname & protocol for your site
twitter_username: togm
github_username:  tmgreen
permalink: /posts/:year/:month/:day/:title
timezone: America/New_York
exclude:
- README.md
- Makefile
- GemFile
- GemFile.lock

# Build settings
markdown: kramdown

